inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - '.*/**/*'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable
  DisplayStyleGuide: true
  # StyleGuideBaseURL: https://rubystyle.guide
  ExtraDetails: true
  TargetRubyVersion: 3.1

# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: TreatCommentsAsGroupSeparators, ConsiderPunctuation, Include.
# Include: **/*.gemfile, **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

# Configuration parameters: EnforcedStyle.
# SupportedStyles: slashes, arguments
Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

# Configuration parameters: AllowedConstants.
Style/Documentation:
  Enabled: false

# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes

# # This cop supports safe auto-correction (--auto-correct).
# # Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# # URISchemes: http, https
# Layout/LineLength:
#   Max: 140
