version: "3.9"

x-services:
  default: &default
    logging:
      options:
        max-size: 1k
    restart: unless-stopped

  development: &development
    <<: *default
    image: rails7_dev:latest
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV:
      RAILS_MASTER_KEY:
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - assets:/app/public/assets
      - storage:/app/storage
    tmpfs:
      - /app/tmp:uid=1000,gid=1000

services:
  ap:
    image: rails7_app:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: production
      RAILS_MASTER_KEY:
    profiles: [production]

  dev:
    <<: *development
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"

volumes:
  bundle:
  node_modules:
  assets:
  storage:
