version: "3.9"

x-services:
  default: &default
    logging:
      options:
        max-size: 1k
    restart: unless-stopped

  development: &development
    <<: *default
    image: rails7_dev:latest
    environment:
      TZ: Asia/Tokyo
      RAILS_MASTER_KEY:
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - storage:/app/storage
    tmpfs:
      - /app/tmp:uid=1000,gid=1000
    tty: true
    stdin_open: true

services:
  ap:
    image: rails7_app:latest
    build:
      context: .
      args:
        RAILS_MASTER_KEY:
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Tokyo
      RAILS_MASTER_KEY:
      RAILS_SERVE_STATIC_FILES: "true"
    volumes:
      - production-db:/app/db
    profiles: [production]

  dev:
    <<: *development
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
      - "3443:3443"

  debug:
    <<: *development
    entrypoint: rdebug-ide --host 0.0.0.0 --port 1234 --
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
      - "1234:1234"
    profiles: [debug]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  bundle:
  node_modules:
  storage:
  production-db:
  keycloak-data:
